### ISSUE TITLE
Add a test for ICMP fragmentation needed DOS attack

### ISSUE THREAD

**Issue by ol-alexandra** [Xilinx-CNS/cns-sapi-ts#83]
Please add a test with ICMP fragmentation needed DOS attack.  The test would create a TCP or UDP connection, and send a lot of such ICMP with different MTUs to IUT referring this connection.  At the end the test should ensure that the connection is still usable.   In a sense, the test would be similar to `attacks/icmp/icmp_flood`.

Iterations:
- TCP or UDP;
- different ranges for MTU in ICMPs: "limited" within 576 - 1500; "unlimited" 0 - 0xffff.

Any additions to the test scenario are welcome.

NB in https://github.com/Xilinx-CNS/onload `ci_ipp_pmtu_rx()` I read:
```
  /* hardly a worth-while dos attack, however ... */
  /* ... (proof that i'm not great at predictions) by april 2005 it was picked
   *  up by the media as part of a world-spanning problem :-) */
```

**Comment by okt-yurijp** [comment]
The test was implemented and added to sapi-ts.
